version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres-financial-tracker
    ports:
      - "5432:5432"  # Локальный порт:Порт контейнера
    environment:
      POSTGRES_USER: tracker_user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: financial_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
